### PR TITLE
Change format without changing output

### PR DESCRIPTION
**Pull request by mechanapoleon**
I'm updating the draw functions so that they can work in mathematica version 12+.

I'll start by improving the code with a more "functional programming approach", so that they are easier to debug and a bit faster.
I'll then move on to change a few of the color functions so that they are a bit less ugly to watch.

### CODE REVIEW

**Comment by jlaragonvera** [comment]
Hi Ismaele, please give a few days to consider your proposal.

**Comment by mechanapoleon** [comment]
@jlaragonvera Hi! Sorry for not contacting you at first. I have been playing with your tools a bit, so I thought that I could do a bit of refactoring and make the visualisation tools work for newer versions of Mathematica. 
I'll be making additional changes in the upcoming days and I'll send you a notebook so that you can test it. 


I'll send you and email and I'll introduce myself if it is fine for you!

**Comment by mechanapoleon** [comment]
@jlaragonvera Hi again! With this changes GADraw works on newer Mathematica versions.

For example:
GADraw[e[1] + e[1] e[2] + e[1] e[2] e[3]]


As for the other changes that you have in mind I'll open a new PR after this is merged.

Let me know if you have any question or comment!

**Comment by mechanapoleon** [comment]
@alejandraortizduran  merged the changes that I made in this PR on the main PR, while fixing a bug.

https://github.com/jlaragonvera/Geometric-Algebra/pull/6

**Pull request closed without merging**
